on: push
name: 'Tag and Publish to Production'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - name: Build
        run: ./scripts/build.sh
  tag_tree:
    runs-on: ubuntu-latest
    name: Tag
    needs: build_tree
    steps:
      - uses: actions/checkout@v2
      - uses: ./scripts/tag.sh
  publish_tree:
    runs-on: ubuntu-latest
    name: Publish
    needs: tag_tree
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: ./scripts/build.sh
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}