on: push
name: 'Tag and Publish to Production'
jobs:
  build_tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Build
        run: ./scripts/build.sh
  tag_tree:
    runs-on: ubuntu-latest
    name: Tag
    needs: build_tree
    steps:
      - uses: actions/checkout@v2
      - name: Tag
        run: ./scripts/tag.sh
  publish_tree:
    runs-on: ubuntu-latest
    name: Publish
    needs: tag_tree
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: ./scripts/build.sh
      - name: Publish
        run: |
          echo //registry.npmjs.org/:_authToken=${SECRET_NPM_TOKEN} > ~/.npmrc
          npm whoami
          npm publish --access public
        env:
          SECRET_NPM_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}